apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: seytech 
  name: nginx-serviceaccount
  labels:
    app: nginx-sts
---
apiVersion: v1
kind: Service
metadata:
  namespace: seytech
  name: nginx-svc
  labels:
    app: nginx-sts
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: seytech 
  name: nginx-sts
spec:
  selector:
    matchLabels:
      app: nginx-sts # has to match .spec.template.metadata.labels
  serviceName: nginx-svc
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: nginx-sts # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: nginx-storage
          persistentVolumeClaim:
            claimName: nginx-pvc
      containers:
      - name: nginx-sts
        image: nginx  #registry.k8s.io
        imagePullPolicy: 
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: nginx-storage
          mountPath: /usr/share/nginx/html
  # volumeClaimTemplates:
  # - metadata:
  #     name: www
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     storageClassName: manual
  #     resources:
  #       requests:
  #         storage: 1Gi