apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: seytech
  name: nginx-deploy
  labels:
    name: nginx-deploy
    tier: frontend
spec:
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      volumes:
        - name: nginx-storage
          persistentVolumeClaim:
            claimName: nginx-pvc
      containers:
        - name: nginx-deploy
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: DEMO_GREETING
              value: "Hello from the environment"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: nginx-storage
