apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: seytech
  name: nginx-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi