apiVersion: v1
kind: Pod
metadata:
  namespace: seytech
  name: nginx-pod
spec:
  volumes:
    - name: nginx-storage
      persistentVolumeClaim:
        claimName: nginx-pvc
  containers:
    - name: task-pv-container
      image: nginx:latest
      ports:
        - containerPort: 80
          name: "web-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-storage