
AWSTemplateFormatVersion: 2010-09-09
Description: "EC2 suites"
Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: "Name of an existing SSH Keypair to access the instance"
    Default: casesuroo
  InstanceType:
    Description: Allowed EC2 instance type
    Type: String
    AllowedValues:
    - t1.micro
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    - m1.small
    - m1.medium
Resources:
  SSHSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      GroupName: SSHSG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 24.12.156.0/16
      Tags:
        - Key: Name
          Value: SSHSecurityGroup
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      KeyName: !Ref KeyName
      InstanceType: "t2.micro"
      ImageId: "ami-02396cdd13e9a1257"
      SecurityGroups: 
        - !Ref SSHSecurityGroup
      Tags:
        - Key: Name
          Value: TestEC2
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags: 
        - Key: Name
          Value: ksultan-bucket100
  EBSVolume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: us-east-1a
      Iops: 3000
      Size: 10
      VolumeType: gp3
      Tags: 
        - Key: Name
          Value: TestVolume