apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: seytech
  name: seytech-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-hostpath-sc
  accessModes:
    - ReadWriteOnce
