apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: test
      image: nginx
      volumeMounts:
        - name: data
          mountPath: /var/nginx/html/
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: task-pv-claim