Parameters:
  EC2InstanceTypes:
    Type: String
    Default: r48.xlarge
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
  EC2PortNumber:
    Type: Number
    Default: 80 
    AllowedValues:
      - 22
      - 80
      - 443
    Description: The port numbers used for Web server EC2 Instance
  
Resources:
  CreateEC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      InstanceType: !Ref EC2InstanceTypes
      ImageId: !Ref LatestAmiId
      IamInstanceProfile: !Ref SessionManagerInstanceProfile
      SecurityGroups:
        - !Ref InstanceSecurityGroup

  CreateEC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      InstanceType: !Ref EC2InstanceTypes
      ImageId: !Ref LatestAmiId
      IamInstanceProfile: !Ref SessionManagerInstanceProfile
      SecurityGroups:
        - !Ref InstanceSecurityGroup
  
  CreateEC2Instance3:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      InstanceType: !Ref EC2InstanceTypes
      ImageId: !Ref LatestAmiId
      IamInstanceProfile: !Ref SessionManagerInstanceProfile
      SecurityGroups:
        - !Ref InstanceSecurityGroup



Parameters:
  LogicalID:
    Type: [ String, Number]



Three different accounts:
  VPC1
  VPC2
  VPC3

You will have a CF template, that creates EC2
- You want to deploy :
    1 EC2 in VPCA
    1 EC2 in VPC2
    1 EC2 in VPC3 
- Make CloudFormation to Find the VPC IDs for you and use it

"Fn::Select"
!Select 


aws cloudformation create-stack, 


!FindInMap [RegionMap, !Ref "AWS::Region", HVM64]


Mappings: --> Section
  RegionMap:  --> LogiaclID
    us-east-1: 
      "HVM64": "ami-0ff8a91507f77f867"
    us-west-1: 
      "HVM64": "ami-0bdb828fd58c52235"
    eu-west-1: 
      "HVM64": "ami-047bb4163c506cd98"
    ap-southeast-1: 
      "HVM64": "ami-08569b978cc4dfa10"
    ap-northeast-1: 
      "HVM64": "ami-06cd52961ce9f0d85"


Resources: 
  myEC2Instance: 
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", HVM64]
      InstanceType: m1.small
